"""70品種をcropsテーブルに追加する。既存品種はスキップ（name重複チェック）。"""
import sqlite3
from datetime import date
from pathlib import Path

DB = Path(__file__).parent / 'vegbook.db'

# (name, category_id, region_id, environment_id, difficulty, days_to_harvest,
#  sow_start, sow_end, harvest_start, harvest_end,
#  sunlight, watering, temp_min, temp_max,
#  seed_or_seedling, price_min, price_max, planter_size,
#  rotation_years, yield_per_plant, storage, harvest_sign, failure_points,
#  name_en, sunlight_en, watering_en, harvest_sign_en, storage_en, failure_points_en)
CROPS = [
    # ── 果菜類 (category_id=1) ──────────────────────────────────────
    ('ズッキーニ', 1, None, 1, 2, 50, 4, 5, 6, 9,
     '直射日光6時間以上必要', '土が乾いたらたっぷり与える。過湿は根腐れの原因',
     18.0, 28.0, '苗（直播きも可）', 150, 300,
     '直径30cm以上の深型プランターまたは畑', 3, '1株あたり10〜20本',
     '冷蔵庫野菜室で3〜5日。鮮度落ちが早いため早めに使用',
     '花が落ちてから5〜7日後、長さ15〜20cmで収穫。大きくなると固くなる',
     '連作障害（うどんこ病）。過湿による根腐れ。実を大きくしすぎると株が疲弊する',
     'Zucchini', 'Full sun (6+ hours)', 'Water when soil surface dries. Avoid waterlogging.',
     'Harvest at 15-20cm after 5-7 days from flower drop', 'Refrigerate up to 5 days',
     'Susceptible to powdery mildew and root rot from overwatering'),
    ('パプリカ', 1, None, 1, 3, 150, 2, 3, 7, 10,
     '直射日光8時間以上。日照不足は着色不良の原因',
     '乾燥に弱い。土の表面が乾いたら与える。真夏は朝夕2回',
     20.0, 28.0, '苗（育苗に時間がかかるため苗購入推奨）', 100, 200,
     '深さ30cm以上の大型プランター（20L以上）', 3, '1株あたり20〜30個',
     '常温で1週間。冷蔵庫野菜室で2週間',
     '緑→黄→赤と色が変わり、完全着色したら収穫。ヘタが乾き始めたら遅い',
     '低温・曇天での着色不良。連作障害（疫病・青枯病）。アブラムシによるウイルス病媒介',
     'Bell Pepper', 'Full sun (8+ hours)', 'Water regularly; twice daily in summer heat.',
     'Harvest when fully colored (red/yellow). Green is underripe.',
     'Room temp 1 week; refrigerate up to 2 weeks',
     'Poor coloring in low temps; viral diseases via aphids'),
    ('唐辛子', 1, None, 1, 2, 120, 3, 4, 7, 10,
     '直射日光6時間以上', '乾燥気味に管理。乾燥しすぎると辛みが増す',
     20.0, 30.0, '苗', 100, 200,
     '深さ20cm以上のプランター', 3, '1株あたり50〜100個',
     '乾燥させて常温で半年以上保存可能。生の場合は冷蔵で1週間',
     '果実が赤く完熟したら収穫。青唐辛子は緑色のうちに収穫',
     '連作障害（疫病・青枯病）。高温期の水切れで過度に辛くなる。アブラムシ被害',
     'Chili Pepper', 'Full sun (6+ hours)', 'Keep slightly dry; drought increases spiciness.',
     'Harvest red for dried; harvest green for fresh use',
     'Dried: 6+ months at room temp; fresh: refrigerate 1 week',
     'Crop rotation needed; aphids spread viruses'),
    ('ゴーヤ', 1, None, 1, 2, 90, 4, 5, 7, 9,
     '直射日光8時間以上。グリーンカーテンにも最適',
     '水を好む。土の表面が乾いたらたっぷりと。真夏は朝夕2回',
     20.0, 30.0, '苗（直播きも可）', 100, 200,
     '深さ30cm以上の大型プランター（30L以上）。ネット・支柱必須', 2, '1株あたり10〜20本',
     '常温で1週間。冷蔵庫野菜室で2週間',
     '果実が15〜20cmで表面が緑色のうちに収穫。黄色くなると苦みが減り種が硬くなる',
     '過湿による根腐れ。ネット設置を忘れると誘引できず収穫量減。うどんこ病',
     'Bitter Melon', 'Full sun (8+ hours). Great as green curtain.',
     'Water generously; twice daily in midsummer.',
     'Harvest green at 15-20cm; yellowing means overripe',
     'Room temp 1 week; refrigerate 2 weeks',
     'Root rot from overwatering; powdery mildew'),
    ('かぼちゃ', 1, None, 1, 2, 90, 4, 5, 7, 9,
     '直射日光8時間以上', '乾燥気味に管理。着果後は水を控えると糖度が上がる',
     18.0, 28.0, 'タネ（直播きまたは育苗）', 100, 200,
     '畑栽培が理想。プランターでは小玉品種を選ぶ（50L以上）', 3, '1株あたり2〜4個',
     '常温で1〜2ヶ月。切り口は冷蔵で1週間',
     '開花から40〜45日後、果梗（コルク化したへた）が茶色くなったら収穫',
     '連作障害（つる割病）。着果不良（人工授粉が必要な場合あり）。過湿による根腐れ',
     'Pumpkin / Kabocha Squash', 'Full sun (8+ hours)',
     'Keep slightly dry; reduce water after fruit set.',
     'Harvest 40-45 days after flowering when stem corks up',
     'Room temp 1-2 months; cut pieces refrigerate 1 week',
     'Fusarium wilt from crop rotation; hand pollination often needed'),
    ('スイカ', 1, None, 1, 3, 90, 4, 5, 7, 8,
     '直射日光8時間以上', '着果前は乾燥気味、着果後は適度な水分を保ち収穫10日前から控える',
     20.0, 30.0, '苗（育苗難のため苗購入推奨）', 200, 400,
     '大型プランター（100L以上）または畑。小玉品種なら50L', 3, '1株あたり1〜3個',
     '常温で1〜2週間。切ったら冷蔵で3〜4日',
     '開花から40〜45日後、巻きひげが茶色く枯れ、叩くと鈍い音がしたら収穫',
     '連作障害（炭疽病・つる割病）。着果管理が難しい（人工授粉必要）。梅雨時期の過湿',
     'Watermelon', 'Full sun (8+ hours)',
     'Keep dry before fruit set; reduce water 10 days before harvest.',
     'Harvest 40-45 days after flowering; tap for hollow sound',
     'Room temp 2 weeks; refrigerate cut pieces 3-4 days',
     'Fusarium wilt; manual pollination often required'),
    ('メロン', 1, None, 1, 3, 90, 4, 5, 7, 8,
     '直射日光8時間以上', '水管理が重要。乾燥気味を基本とし、着果後は適度に。収穫前2週間は断水気味',
     22.0, 30.0, '苗（育苗が難しいため苗購入推奨）', 200, 500,
     '大型プランター（100L以上）または温室・ビニールトンネル', 3, '1株あたり1〜2個',
     '常温で追熟（3〜7日）。冷蔵庫で冷やしてから食べる',
     '開花から45〜50日後、ネット（網目模様）が均一に発達し甘い香りがしたら収穫',
     '連作障害（つる割病）。水管理ミスによる裂果。高湿度でうどんこ病・炭疽病',
     'Muskmelon', 'Full sun (8+ hours)',
     'Critical water management; keep dry especially 2 weeks before harvest.',
     'Harvest 45-50 days after flowering; uniform netting pattern and sweet aroma',
     'Ripen at room temp 3-7 days; then refrigerate',
     'Fusarium wilt; cracking from improper watering; powdery mildew'),
    ('いちご', 1, None, 2, 2, 180, 9, 10, 4, 6,
     '日当たりの良い場所。半日陰でも栽培できるが収量が落ちる',
     '土の表面が乾いたらたっぷりと。花・果実に水がかからないよう根元に与える',
     5.0, 20.0, '苗（ランナーで増やすことも可能）', 200, 500,
     '深さ20cm以上のプランターまたは専用いちごプランター', 2, '1株あたり10〜20個',
     '常温で1〜2日。冷蔵庫で2〜3日。冷凍保存可（1ヶ月）',
     '果実が全体的に赤く色づき、ヘタの付け根まで赤くなったら収穫。朝の収穫が甘い',
     'うどんこ病・灰色かび病（高湿度）。ランナーを放置すると株が消耗する。鳥害',
     'Strawberry', 'Good sunlight preferred; tolerates partial shade',
     'Water at base; avoid wetting flowers and fruit.',
     'Harvest when fully red including near the calyx; morning harvest is sweetest',
     'Room temp 1-2 days; refrigerate 2-3 days; freeze up to 1 month',
     'Powdery mildew and botrytis in high humidity; remove runners to prevent exhaustion'),
    ('アスパラガス', 1, None, 1, 3, 730, 3, 4, 4, 6,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと。夏の乾燥に注意',
     10.0, 25.0, '種（2〜3年育苗）または株（収穫まで早い）', 300, 800,
     '深さ40cm以上の大型プランターまたは畑（多年草）', 0, '1株あたり5〜10本（収穫期）',
     '冷蔵庫の野菜室で3〜4日。立てて保存すると長持ち',
     '太さが1cm以上の若芽を地際で切る。伸びすぎると固くなる',
     '株の充実に2〜3年かかる。立茎を刈り込みすぎると翌年の収量が落ちる。茎枯病',
     'Asparagus', 'Full sun (6+ hours)',
     'Water when soil surface dries; watch for summer drought.',
     'Cut spears at soil level when 1cm+ thick; overgrown spears become tough',
     'Refrigerate upright 3-4 days',
     'Takes 2-3 years to establish; do not over-harvest; stem blight'),
    ('冬瓜', 1, None, 1, 2, 100, 4, 5, 7, 9,
     '直射日光8時間以上', '水を好む。土の表面が乾いたらたっぷりと',
     20.0, 30.0, 'タネ（直播きまたは育苗）', 100, 200,
     '大型プランター（100L以上）または畑。つる性のため支柱かネット必須', 3, '1株あたり2〜5個',
     '丸ごとなら常温で2〜3ヶ月。切り口は冷蔵で1週間',
     '果実の表面に白い粉が吹いてきたら収穫適期。開花後40〜50日が目安',
     '連作障害（つる割病）。受粉不良による着果失敗。過湿による根腐れ',
     'Winter Melon / Wax Gourd', 'Full sun (8+ hours)',
     'Water generously when soil surface dries.',
     'Harvest 40-50 days after flowering when white bloom appears on skin',
     'Whole: room temp 2-3 months; cut: refrigerate 1 week',
     'Fusarium wilt from crop rotation; poor pollination; root rot'),
    ('へちま', 1, None, 1, 2, 90, 4, 5, 8, 10,
     '直射日光8時間以上。グリーンカーテンにも利用可',
     '水を好む。土の表面が乾いたらたっぷりと。真夏は朝夕2回',
     20.0, 30.0, 'タネ（直播きまたは育苗）', 100, 200,
     '大型プランター（50L以上）または畑。支柱・ネット必須', 2, '1株あたり10〜20本',
     '食用は20〜30cm（柔らかいうちに）。たわし用は完熟させる',
     '食用は20〜30cmで表面が緑色のうちに収穫。固くなると食べられない',
     'うどんこ病（高温乾燥期）。実を大きくしすぎると株が疲弊する',
     'Sponge Gourd / Luffa', 'Full sun (8+ hours). Suitable as green curtain.',
     'Water generously; twice daily in midsummer.',
     'Harvest at 20-30cm while still green and tender',
     'Eat fresh within a few days; let fully ripen for loofah sponge',
     'Powdery mildew in dry heat; overripening exhausts the plant'),

    # ── 葉モノ野菜 (category_id=2) ──────────────────────────────────
    ('チンゲン菜', 2, None, 2, 1, 45, 3, 10, 5, 12,
     '日当たりの良い場所が理想。半日陰でも育つ',
     '土の表面が乾いたらたっぷりと。過湿は根腐れの原因',
     5.0, 25.0, 'タネ（直播き）', 100, 200,
     '深さ15cm以上のプランター。条間15cmで点播き', 1, '1株あたり100〜200g',
     '冷蔵庫野菜室で3〜5日。茹でて冷凍可（1ヶ月）',
     '草丈20〜25cm、葉が肉厚で光沢があるときが収穫適期',
     '高温（25℃超）でのとう立ち。過湿による軟腐病。連作によるコナガ被害',
     'Bok Choy', 'Full sun preferred; tolerates partial shade',
     'Water when soil surface dries; avoid waterlogging.',
     'Harvest at 20-25cm when leaves are thick and glossy',
     'Refrigerate 3-5 days; blanch and freeze up to 1 month',
     'Bolts in high heat; soft rot from waterlogging'),
    ('春菊', 2, None, 2, 1, 40, 9, 10, 10, 12,
     '日当たりの良い場所。半日陰でも育つ',
     '土の表面が乾いたらたっぷりと。乾燥させると苦みが増す',
     5.0, 20.0, 'タネ（直播き）', 100, 150,
     '深さ15cm以上のプランター。筋播きまたは条播き', 1, '1株あたり30〜50g（摘み取り収穫）',
     '冷蔵庫野菜室で2〜3日。香りが飛びやすいため早めに使用',
     '草丈10〜15cmで摘み取り収穫。脇芽が伸びて繰り返し収穫できる',
     '高温（20℃超）でのとう立ち。寒冷地では霜対策が必要。密植による蒸れ',
     'Edible Chrysanthemum / Garland Chrysanthemum', 'Full sun; tolerates partial shade',
     'Water when soil surface dries; drought increases bitterness.',
     'Harvest at 10-15cm by pinching; side shoots regrow for repeated harvests',
     'Refrigerate 2-3 days; aroma fades quickly',
     'Bolts above 20°C; protect from frost in cold regions'),
    ('水菜', 2, None, 2, 1, 40, 3, 10, 5, 12,
     '日当たりの良い場所が最適。半日陰でも育つ',
     '土の表面が乾いたらたっぷりと。乾燥に比較的強い',
     5.0, 25.0, 'タネ（直播き）', 100, 150,
     '深さ15cm以上のプランター。条播きで株間15cm', 1, '1株あたり200〜400g',
     '冷蔵庫野菜室で3〜5日',
     '草丈20〜30cmで株ごと収穫、または外葉から摘み取り収穫',
     '高温・多湿での軟腐病。密植すると蒸れて病気が出やすい',
     'Mizuna / Japanese Mustard Greens', 'Full sun preferred; tolerates partial shade',
     'Water when surface dries; relatively drought-tolerant.',
     'Harvest whole at 20-30cm or pick outer leaves as needed',
     'Refrigerate 3-5 days',
     'Soft rot in heat and humidity; thin to prevent crowding'),
    ('ルッコラ', 2, None, 2, 1, 40, 3, 5, 5, 6,
     '日当たりの良い場所。強い日差しは避ける（半日陰でも可）',
     '土の表面が乾いたらたっぷりと。乾燥すると辛みが増す',
     5.0, 25.0, 'タネ（直播き）', 100, 150,
     '深さ15cm以上のプランター。筋播きで株間5〜10cm', 1, '1株あたり30〜50g（摘み取り）',
     '冷蔵庫野菜室で2〜3日。すぐにしおれやすい',
     '草丈10〜15cmで外葉から摘み取り収穫。花芽が出る前が最も風味が良い',
     '高温（25℃超）でのとう立ち・辛み強化。アブラムシ被害。連作による根こぶ病',
     'Arugula / Rocket', 'Full sun; avoid intense midday sun (partial shade OK)',
     'Water when surface dries; drought increases peppery taste.',
     'Harvest outer leaves at 10-15cm before bolting for best flavor',
     'Refrigerate 2-3 days; wilts quickly',
     'Bolts in heat; aphids; clubroot from continuous cropping'),
    ('スイスチャード', 2, None, 2, 1, 50, 4, 6, 6, 10,
     '日当たりの良い場所。半日陰でも育つ',
     '土の表面が乾いたらたっぷりと。過湿に注意',
     5.0, 28.0, 'タネ（直播きまたは育苗）', 100, 200,
     '深さ20cm以上のプランター。株間20〜25cm', 1, '1株あたり400〜600g（摘み取り）',
     '冷蔵庫野菜室で3〜5日',
     '草丈20〜30cmで外葉から摘み取り収穫。長期間繰り返し収穫できる',
     '密植による蒸れ・腐敗。高温多湿で斑点病が出やすい',
     'Swiss Chard', 'Full sun; tolerates partial shade',
     'Water when surface dries; avoid waterlogging.',
     'Harvest outer leaves at 20-30cm; long harvest period',
     'Refrigerate 3-5 days',
     'Crowding causes rot; leaf spot in hot humid conditions'),
    ('ケール', 2, None, 1, 2, 60, 4, 5, 7, 11,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     0.0, 25.0, 'タネ（育苗）または苗', 100, 200,
     '深さ30cm以上のプランターまたは畑。株間40〜50cm', 2, '1株あたり1〜2kg（摘み取り）',
     '冷蔵庫野菜室で5〜7日。スムージー用は洗って冷凍可',
     '草丈40〜50cmで外葉から摘み取り収穫。霜に当たると甘みが増す',
     '高温多湿での病害。アオムシ・コナガの食害。密植による蒸れ',
     'Kale', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest outer leaves at 40-50cm; frost improves sweetness',
     'Refrigerate 5-7 days; freeze for smoothies',
     'Caterpillar damage; fungal disease in hot humid conditions'),
    ('芽キャベツ', 2, None, 1, 3, 150, 6, 7, 11, 2,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと。乾燥に強い',
     0.0, 20.0, '苗（育苗期間が長いため苗購入推奨）', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間50cm以上。支柱が必要', 3, '1株あたり50〜80個',
     '冷蔵庫野菜室で2〜3週間。冷凍保存可（ブランチング後）',
     '下から順に膨らみ、直径2〜3cmになったら収穫。霜に当たると甘みが増す',
     '連作障害（根こぶ病）。強風で株が倒れやすい（支柱必須）。アオムシ被害',
     'Brussels Sprouts', 'Full sun (6+ hours)',
     'Water when surface dries; drought-tolerant.',
     'Harvest from bottom up when sprouts reach 2-3cm; frost improves flavor',
     'Refrigerate 2-3 weeks; freeze after blanching',
     'Clubroot from crop rotation; needs staking; caterpillar damage'),
    ('パクチョイ', 2, None, 2, 1, 40, 3, 10, 5, 12,
     '日当たりの良い場所。半日陰でも育つ',
     '土の表面が乾いたらたっぷりと',
     5.0, 25.0, 'タネ（直播き）', 100, 150,
     '深さ15cm以上のプランター。株間15〜20cm', 1, '1株あたり100〜200g',
     '冷蔵庫野菜室で3〜5日',
     '草丈15〜20cmで株ごと収穫',
     '高温でのとう立ち。過湿による軟腐病',
     'Pak Choi / Baby Bok Choy', 'Full sun; tolerates partial shade',
     'Water when surface dries.',
     'Harvest whole plant at 15-20cm',
     'Refrigerate 3-5 days',
     'Bolts in heat; soft rot from overwatering'),
    ('からし菜', 2, None, 1, 1, 40, 3, 4, 4, 5,
     '日当たりの良い場所が最適', '土の表面が乾いたらたっぷりと',
     5.0, 20.0, 'タネ（直播き）', 100, 150,
     '深さ15cm以上のプランターまたは畑', 1, '1株あたり200〜400g',
     '冷蔵庫野菜室で3〜5日',
     '草丈20〜30cmで収穫。若い葉は辛みが少ない',
     '高温でのとう立ち。アブラムシ被害',
     'Mustard Greens', 'Full sun preferred',
     'Water when surface dries.',
     'Harvest at 20-30cm; young leaves are less pungent',
     'Refrigerate 3-5 days',
     'Bolts in heat; aphids'),
    ('セロリ', 2, None, 1, 3, 120, 3, 4, 9, 11,
     '日当たりの良い場所。強い直射日光より半日陰が理想',
     '水を大量に必要とする。土を常に湿らせた状態で管理',
     10.0, 20.0, '苗（育苗が難しいため苗購入推奨）', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間30cm', 3, '1株あたり1本（株全体で500g〜1kg）',
     '冷蔵庫野菜室で1〜2週間',
     '株が60〜70cmになったら外側の茎から収穫。全体が充実したら株ごと収穫',
     '水切れによる苦み・筋が多くなる。高温でのとう立ち。軟腐病（過湿）',
     'Celery', 'Good light; partial shade better than intense sun',
     'Needs constant moisture; keep soil evenly wet.',
     'Harvest outer stalks at 60-70cm or cut whole plant',
     'Refrigerate 1-2 weeks',
     'Bitterness from water stress; bolts in heat; soft rot'),
    ('フキ', 2, None, 1, 2, 365, 9, 11, 3, 5,
     '半日陰でも育つ。直射日光より木陰のような環境が理想',
     '水を好む。土を乾かさないよう管理',
     0.0, 20.0, '株（根茎）', 200, 500,
     '畑栽培または大型プランター（50L以上）。多年草で毎年収穫可', 0, '1株あたり10〜30本/年',
     '冷蔵庫野菜室で3〜5日。灰汁抜き必要',
     '葉が展開し始めた若い茎（フキノトウ：2〜3月）または葉柄（4〜5月）を収穫',
     '直射日光による葉焼け。乾燥による生育不良。株の老化（3〜4年ごとに株分け）',
     'Japanese Butterbur', 'Tolerates shade; prefers dappled light',
     'Keep soil consistently moist.',
     'Harvest fuki-no-to (flower buds) Feb-Mar; leaf stalks Apr-May',
     'Refrigerate 3-5 days; requires blanching to remove bitterness',
     'Leaf scorch in direct sun; divide clumps every 3-4 years'),
    ('ニラ', 2, None, 2, 1, 90, 3, 4, 6, 10,
     '日当たりの良い場所。半日陰でも育つ',
     '乾燥に強い。土の表面が乾いたらたっぷりと',
     0.0, 30.0, 'タネまたは株（株分けが手軽）', 100, 200,
     '深さ15cm以上のプランター。多年草で毎年収穫可', 0, '株あたり年間複数回収穫',
     '冷蔵庫野菜室で3〜5日。刻んで冷凍可',
     '草丈20〜25cmで地際から3〜5cm残して刈り取り。年3〜4回収穫できる',
     '花が咲くと葉が固くなる（花茎は早めに切る）。株の老化（3〜4年ごとに株分け）',
     'Chinese Chives / Garlic Chives', 'Full sun; tolerates partial shade',
     'Drought-tolerant; water when surface dries.',
     'Cut at 20-25cm leaving 3-5cm stub; harvest 3-4 times per year',
     'Refrigerate 3-5 days; chop and freeze',
     'Flower stalks harden leaves; divide clumps every 3-4 years'),
    ('ブロッコリー', 2, None, 1, 2, 90, 7, 8, 10, 12,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと',
     5.0, 20.0, '苗', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間40〜50cm', 3, '1株あたり頂花蕾300〜500g＋側花蕾',
     '冷蔵庫野菜室で4〜5日。茹でて冷凍可（1ヶ月）',
     '花蕾が直径15〜20cmで固く締まっているうちに収穫。黄色くなると食味が落ちる',
     '連作障害（根こぶ病）。アオムシ・コナガの食害。高温では結球不良',
     'Broccoli', 'Full sun (6+ hours)',
     'Water when surface dries.',
     'Harvest head at 15-20cm while still compact and dark green',
     'Refrigerate 4-5 days; blanch and freeze up to 1 month',
     'Clubroot; caterpillar damage; poor head formation in heat'),
    ('カリフラワー', 2, None, 1, 3, 90, 7, 8, 10, 12,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと',
     5.0, 20.0, '苗', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間50cm', 3, '1株あたり1個（400〜700g）',
     '冷蔵庫野菜室で1週間。茹でて冷凍可',
     '花蕾が直径15〜20cmで白く締まっているうちに収穫。日光に当てると黄変する',
     '連作障害（根こぶ病）。直射日光による花蕾の黄変（葉でカバーする）。アオムシ',
     'Cauliflower', 'Full sun (6+ hours)',
     'Water when surface dries.',
     'Harvest head at 15-20cm while white and compact; cover with leaves to prevent yellowing',
     'Refrigerate 1 week; blanch and freeze',
     'Clubroot; blanch heads to prevent yellowing; caterpillar damage'),
    ('クレソン', 2, None, 2, 1, 40, 3, 5, 5, 7,
     '半日陰が理想。直射日光より涼しい環境を好む',
     '水を非常に好む。土を常に湿らせた状態で管理。水耕栽培も可能',
     5.0, 20.0, 'タネまたは挿し芽（スーパーで買ったものを水に挿すと発根する）', 100, 200,
     '浅いプランターで水耕栽培も可能。水はけの悪い用土でもOK', 1, '1株あたり30〜50g（摘み取り）',
     '冷蔵庫野菜室で2〜3日。水に浸けて保存すると長持ち',
     '草丈10〜15cmで摘み取り収穫。花芽が出る前が最も風味が良い',
     '高温（25℃超）でのとう立ち・苦み増加。乾燥による枯れ',
     'Watercress', 'Partial shade preferred; cool environment',
     'Keep constantly moist; suitable for hydroponic growing.',
     'Harvest tips at 10-15cm before flowering for best flavor',
     'Refrigerate 2-3 days; store in water to extend shelf life',
     'Bolts and becomes bitter in heat; wilts without moisture'),

    # ── 根菜類 (category_id=3) ──────────────────────────────────────
    ('ビーツ', 3, None, 1, 2, 60, 3, 4, 5, 7,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと。過湿は根腐れの原因',
     5.0, 25.0, 'タネ（直播き）', 100, 200,
     '深さ25cm以上のプランターまたは畑。株間15cm', 2, '1株あたり100〜200g',
     '冷蔵庫野菜室で2〜3週間。茹でて冷凍可（2ヶ月）',
     '根の直径が5〜7cmになったら収穫。大きくなりすぎると固くなる',
     '酸性土壌で生育不良（pH6.0〜7.0必要）。過湿による根腐れ。葉が食用にもなる',
     'Beetroot', 'Full sun (6+ hours)',
     'Water when surface dries; avoid waterlogging.',
     'Harvest roots at 5-7cm diameter; larger roots become tough',
     'Refrigerate 2-3 weeks; cook and freeze up to 2 months',
     'Needs neutral to alkaline soil (pH 6.0-7.0); root rot from waterlogging'),
    ('ターニップ', 3, None, 1, 1, 50, 3, 4, 5, 6,
     '日当たりの良い場所', '土の表面が乾いたらたっぷりと',
     5.0, 20.0, 'タネ（直播き）', 100, 150,
     '深さ20cm以上のプランターまたは畑。株間15cm', 1, '1株あたり100〜300g',
     '冷蔵庫野菜室で2〜3週間',
     '根の直径が5〜8cmになったら収穫。若い葉も食用になる',
     '高温でのとう立ち。過湿による根腐れ',
     'Turnip', 'Full sun',
     'Water when surface dries.',
     'Harvest roots at 5-8cm; young leaves are also edible',
     'Refrigerate 2-3 weeks',
     'Bolts in heat; root rot from excess moisture'),
    ('パースニップ', 3, None, 1, 2, 120, 3, 4, 9, 11,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     0.0, 20.0, 'タネ（直播き・発芽率が低いため多めに播く）', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間10〜15cm', 2, '1株あたり150〜300g',
     '冷蔵庫野菜室で3〜4週間。霜に当たると甘みが増す',
     '根の太さが直径3〜4cmになったら収穫。霜後の収穫が最も甘い',
     '発芽率が低い（古い種は特に）。肥えすぎた土では又根になる。キアゲハの幼虫被害',
     'Parsnip', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Harvest roots at 3-4cm diameter; frost improves sweetness',
     'Refrigerate 3-4 weeks; sweetens after frost',
     'Poor germination rate; rich soil causes forked roots; swallowtail caterpillars'),
    ('レンコン', 3, None, 1, 3, 150, 4, 5, 9, 11,
     '直射日光8時間以上', '水生植物。水深10〜15cmを維持する',
     15.0, 30.0, '種レンコン（節がある親株）', 300, 600,
     '大型の水槽・睡蓮鉢（100L以上）または水田', 3, '1株あたり1〜3節',
     '冷蔵庫野菜室で1〜2週間。水に浸けて保存すると変色を防げる',
     '葉が枯れ始めた秋〜冬に泥の中から収穫。折れないよう丁寧に掘る',
     '水量管理が難しい。泥の中での栽培で管理が大変。病害（腐敗病）',
     'Lotus Root', 'Full sun (8+ hours)',
     'Aquatic plant; maintain 10-15cm water depth.',
     'Harvest in autumn when leaves die back; dig carefully to avoid breaking',
     'Refrigerate 1-2 weeks; store in water to prevent browning',
     'Water level management; muddy conditions; rot disease'),
    ('ゴボウ', 3, None, 1, 2, 120, 3, 4, 10, 12,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     10.0, 25.0, 'タネ（直播き）', 100, 200,
     '深さ60〜80cm以上の深型プランターまたは袋栽培。短根品種が家庭向き', 3, '1株あたり100〜200g',
     '土の中に埋めたまま保存（2〜3ヶ月）。掘り出したら冷蔵庫で1〜2週間',
     '葉が枯れ始め、根が直径2〜3cmになったら収穫',
     '深い根が必要（浅いプランターでは育たない）。キアゲハの幼虫食害。土が固いと形が悪くなる',
     'Burdock Root', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Harvest in autumn when leaves wither and roots reach 2-3cm diameter',
     'Store in soil up to 3 months; refrigerate once harvested for 1-2 weeks',
     'Needs deep soil (60-80cm); caterpillar damage; compacted soil deforms roots'),
    ('ミョウガ', 3, None, 1, 1, 365, 3, 4, 7, 9,
     '半日陰が理想。直射日光より涼しい環境を好む',
     '水を好む。土を乾かさないよう管理',
     10.0, 28.0, '根茎（株分け）', 200, 400,
     '畑栽培または大型プランター（50L以上）。多年草で毎年収穫可', 0, '1株あたり10〜30個/年',
     '冷蔵庫野菜室で3〜5日',
     '花穂が地表に出てきて、つぼみが開く直前に収穫（8〜9月が最盛期）',
     '直射日光による葉焼け。乾燥による生育不良。株の老化（3〜4年ごとに株分け）',
     'Japanese Ginger / Myoga', 'Partial shade preferred; cool environment',
     'Keep soil consistently moist.',
     'Harvest when flower buds emerge but before opening (Aug-Sep)',
     'Refrigerate 3-5 days',
     'Leaf scorch in direct sun; divide clumps every 3-4 years'),
    ('ラッキョウ', 3, None, 1, 2, 270, 8, 9, 5, 6,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     10.0, 28.0, '球根（鱗茎）', 150, 300,
     '深さ20cm以上のプランターまたは畑。株間10〜15cm', 2, '1株あたり10〜20球',
     '漬物加工後は長期保存可。生のまま冷蔵で1〜2週間',
     '葉が黄色くなり始めた初夏に収穫。小粒のうちが甘酢漬けに最適',
     '過湿による腐敗。収穫が遅れると球が割れる',
     'Rakkyo / Chinese Shallot', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest in early summer when leaves yellow; small bulbs best for pickling',
     'Pickled: long-term storage; fresh: refrigerate 1-2 weeks',
     'Rot from waterlogging; cracking if harvested too late'),
    ('コールラビ', 3, None, 1, 2, 60, 3, 4, 5, 6,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと',
     5.0, 22.0, '苗または種（直播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。株間20〜25cm', 2, '1株あたり200〜400g',
     '冷蔵庫野菜室で2〜3週間',
     '茎が直径5〜8cmに膨らんだら収穫。大きくなりすぎると固くなる',
     '高温でのとう立ち。連作障害（根こぶ病）',
     'Kohlrabi', 'Full sun (6+ hours)',
     'Water when surface dries.',
     'Harvest when stem swells to 5-8cm diameter; larger becomes tough',
     'Refrigerate 2-3 weeks',
     'Bolts in heat; clubroot from continuous cropping'),
    ('セロリアック', 3, None, 1, 3, 150, 2, 3, 9, 11,
     '直射日光6時間以上', '水を好む。土を常に湿らせた状態で管理',
     5.0, 20.0, '苗（育苗が難しいため苗購入推奨）', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間30〜40cm', 3, '1株あたり300〜600g',
     '冷蔵庫野菜室で2〜3週間',
     '根が直径8〜12cmになったら収穫。霜前に収穫する',
     '高温での生育不良。水切れによる成長停止。根が浮き上がる（土寄せが必要）',
     'Celeriac / Celery Root', 'Full sun (6+ hours)',
     'Keep soil consistently moist.',
     'Harvest when root reaches 8-12cm diameter before frost',
     'Refrigerate 2-3 weeks',
     'Poor growth in heat; needs consistent watering; hill up soil around root'),
    ('ワサビ', 3, None, 1, 3, 365, 3, 4, 10, 12,
     '半日陰の涼しい環境。渓流沿いのような場所が理想',
     '清流に近い環境。常に冷涼な水分を保つ',
     5.0, 15.0, '株（根茎）', 500, 1000,
     '水はけが良く冷涼な畑または渓流脇。家庭では難しい', 0, '1株あたり50〜100g',
     '冷蔵庫で1〜2週間。すりおろしたものは冷凍可',
     '根茎が直径3〜4cmになったら収穫（1〜2年かかる）。葉・茎も食用可',
     '高温・直射日光で枯れる。清流以外では育ちにくい。栽培難易度が非常に高い',
     'Wasabi', 'Partial shade; cool, moist environment like streamside',
     'Needs cool, constantly moist conditions similar to a mountain stream.',
     'Harvest rhizome when 3-4cm diameter (takes 1-2 years); leaves and stems also edible',
     'Refrigerate 1-2 weeks; freeze grated',
     'Dies in heat or direct sun; very difficult outside its natural habitat'),

    # ── ハーブ (category_id=4) ──────────────────────────────────────
    ('シソ', 4, None, 2, 1, 60, 4, 6, 7, 10,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと。乾燥に弱い',
     18.0, 30.0, 'タネ（直播きまたは育苗）', 100, 200,
     '深さ20cm以上のプランター。株間20〜30cm', 1, '1株あたり葉多数（収穫期間中随時）',
     '冷蔵庫野菜室で3〜5日。水に浸けて保存。冷凍可（刻んで）',
     '草丈20〜30cmで葉を随時摘み取り収穫。花穂が出る前が最も香りが良い',
     '花穂を放置すると葉が固くなる（早めに摘む）。乾燥による葉焼け',
     'Japanese Perilla / Shiso', 'Full sun (6+ hours)',
     'Water when surface dries; sensitive to drought.',
     'Pick leaves as needed; harvest before flowering for best aroma',
     'Refrigerate 3-5 days in water; chop and freeze',
     'Leaves toughen if allowed to flower; leaf scorch from drought'),
    ('バジル', 4, None, 2, 1, 60, 5, 6, 7, 9,
     '直射日光6時間以上。高温を好む',
     '土の表面が乾いたらたっぷりと。水切れで香りが落ちる',
     18.0, 30.0, 'タネ（育苗）または苗', 100, 200,
     '深さ20cm以上のプランター。株間20〜30cm', 1, '1株あたり葉多数（摘み取り）',
     '常温保存（冷蔵庫では黒変する）。水に挿して常温2〜3日',
     '草丈20〜30cmで葉を随時摘み取り。花穂が出たら摘み取って葉の収穫を延ばす',
     '低温（15℃以下）で黒変・枯れる。花穂を放置すると葉が減る',
     'Basil', 'Full sun (6+ hours); loves warmth',
     'Water when surface dries; drought reduces aroma.',
     'Pick leaves as needed; pinch out flowers to extend leaf harvest',
     'Keep at room temp; refrigeration blackens leaves; store in water 2-3 days',
     'Blackens below 15°C; flower production reduces leaf growth'),
    ('パセリ', 4, None, 2, 2, 90, 3, 5, 6, 10,
     '日当たりの良い場所。半日陰でも育つ',
     '乾燥に弱い。土の表面が乾いたらたっぷりと',
     5.0, 25.0, 'タネ（発芽まで3〜4週間かかる）または苗', 100, 200,
     '深さ20cm以上のプランター。株間20〜25cm', 2, '1株あたり葉多数（摘み取り）',
     '冷蔵庫野菜室で3〜5日。水に浸けて保存',
     '外葉から随時摘み取り収穫。2年草で2年目に花を咲かせ枯れる',
     '発芽が遅い・不均一。高温多湿での根腐れ。アゲハチョウの幼虫に食べられやすい',
     'Parsley', 'Full sun; tolerates partial shade',
     'Drought-sensitive; water when surface dries.',
     'Pick outer leaves regularly; biennial - flowers and dies in year 2',
     'Refrigerate 3-5 days in water',
     'Slow uneven germination; root rot in heat; swallowtail caterpillars'),
    ('ミント', 4, None, 2, 1, 60, 3, 5, 6, 10,
     '半日陰でも育つ。直射日光より涼しい環境が理想',
     '水を好む。土の表面が乾いたらたっぷりと',
     5.0, 28.0, '苗（地下茎で急速に広がるため鉢植え推奨）', 100, 200,
     '深さ20cm以上のプランター（地植えは制御が難しい）', 0, '随時摘み取り可',
     '冷蔵庫野菜室で3〜5日。乾燥保存可',
     '草丈10〜15cmで茎ごと摘み取り収穫。花穂は早めに摘む',
     '地下茎が広がり他の植物を圧迫する（必ずプランター管理）。高温多湿での病害',
     'Mint', 'Tolerates partial shade; prefers cool conditions',
     'Keep soil moist.',
     'Harvest stems at 10-15cm; pinch flowers early to maintain leaf production',
     'Refrigerate 3-5 days; dry for storage',
     'Invasive via underground rhizomes (must contain in pots); fungal disease in heat'),
    ('ローズマリー', 4, None, 2, 2, 365, 3, 5, 6, 12,
     '直射日光6時間以上。乾燥した環境を好む',
     '乾燥に強い。水のやりすぎは厳禁。土が乾いてからたっぷりと',
     0.0, 30.0, '苗', 200, 400,
     '深さ20cm以上のプランター。排水性の良い用土が必須', 0, '随時剪定・収穫可（多年草）',
     '常温で1〜2週間（そのまま）。乾燥保存・冷凍可',
     '新芽の先端を随時摘み取り。春〜秋が最も香りが良い',
     '過湿による根腐れ（最も注意が必要）。排水不良の用土では必ず枯れる',
     'Rosemary', 'Full sun (6+ hours); likes dry conditions',
     'Drought-tolerant; water only when soil is completely dry.',
     'Harvest shoot tips regularly; most aromatic spring through autumn',
     'Room temp 1-2 weeks; dry or freeze',
     'Root rot from overwatering is the main killer; must have well-draining soil'),
    ('タイム', 4, None, 2, 1, 365, 3, 5, 5, 11,
     '直射日光6時間以上', '乾燥に強い。土が乾いてからたっぷりと',
     0.0, 28.0, '苗', 150, 300,
     '深さ15cm以上のプランター。排水性の良い用土', 0, '随時剪定・収穫可（多年草）',
     '常温で1週間。乾燥保存可',
     '花が咲く直前が最も香りが良い。茎ごと刈り取って収穫',
     '過湿による根腐れ。梅雨時期の蒸れに注意',
     'Thyme', 'Full sun (6+ hours)',
     'Drought-tolerant; water when soil is dry.',
     'Harvest stems just before flowering for peak aroma',
     'Room temp 1 week; dry for long-term storage',
     'Root rot from overwatering; watch for fungal disease in rainy season'),
    ('オレガノ', 4, None, 2, 1, 365, 3, 5, 6, 10,
     '直射日光6時間以上', '乾燥に強い。土が乾いてからたっぷりと',
     5.0, 30.0, '苗', 150, 300,
     '深さ15cm以上のプランター。排水性の良い用土', 0, '随時剪定・収穫可（多年草）',
     '常温で1〜2週間。乾燥保存可',
     '花が咲く直前が最も香りが強い。茎ごと刈り取り',
     '過湿による根腐れ。梅雨時期の蒸れ',
     'Oregano', 'Full sun (6+ hours)',
     'Drought-tolerant; water when soil dries out.',
     'Harvest stems just before flowering for strongest flavor',
     'Room temp 1-2 weeks; excellent for drying',
     'Root rot from overwatering; summer humidity causes rot'),
    ('チャイブ', 4, None, 2, 1, 60, 3, 5, 6, 10,
     '日当たりの良い場所。半日陰でも育つ',
     '乾燥に強い。土の表面が乾いたらたっぷりと',
     0.0, 25.0, 'タネまたは株分け', 100, 200,
     '深さ15cm以上のプランター。多年草で毎年収穫可', 0, '随時摘み取り可（年3〜4回刈り込み）',
     '冷蔵庫野菜室で3〜5日。刻んで冷凍可',
     '草丈15〜20cmで地際から3〜5cm残して刈り取り。年に何度でも収穫できる',
     '高温多湿での病害。株の老化（2〜3年ごとに株分け推奨）',
     'Chives', 'Full sun; tolerates partial shade',
     'Drought-tolerant; water when surface dries.',
     'Cut at 15-20cm, leaving 3-5cm stub; harvest multiple times per year',
     'Refrigerate 3-5 days; chop and freeze',
     'Fungal disease in hot humid conditions; divide every 2-3 years'),
    ('コリアンダー', 4, None, 2, 1, 40, 3, 5, 5, 7,
     '日当たりの良い場所', '乾燥に弱い。土の表面が乾いたらたっぷりと',
     10.0, 25.0, 'タネ（直播き。移植を嫌う）', 100, 150,
     '深さ20cm以上のプランター。株間15〜20cm', 1, '1株あたり葉多数（摘み取り）',
     '冷蔵庫野菜室で2〜3日。水に浸けて保存。根ごと冷蔵が最も長持ち',
     '草丈15〜20cmで葉を随時収穫。花穂が出る前が最も香りが良い',
     '高温（25℃超）でのとう立ち。移植を嫌うため直播きが基本',
     'Coriander / Cilantro', 'Full sun',
     'Drought-sensitive; water when surface dries.',
     'Pick leaves at 15-20cm before flowering for best aroma',
     'Refrigerate 2-3 days in water; store with roots for longer life',
     'Bolts quickly in heat; dislikes transplanting - direct sow only'),
    ('ディル', 4, None, 2, 1, 60, 3, 5, 5, 8,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     10.0, 25.0, 'タネ（直播き。移植を嫌う）', 100, 150,
     '深さ25cm以上のプランター。株間20〜25cm', 1, '1株あたり葉・種（収穫期間中随時）',
     '冷蔵庫野菜室で3〜5日。種は常温で1年保存可',
     '草丈20〜30cmで葉を随時収穫。花が咲いたら種も収穫できる',
     '高温でのとう立ち。移植を嫌う。フェンネルと交雑するため近くに植えない',
     'Dill', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Pick leaves from 20-30cm; harvest seeds after flowering',
     'Refrigerate leaves 3-5 days; seeds store room temp 1 year',
     'Bolts in heat; dislikes transplanting; cross-pollinates with fennel'),
    ('フェンネル', 4, None, 1, 2, 90, 3, 5, 6, 9,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     5.0, 28.0, 'タネ（直播きまたは育苗）', 150, 300,
     '深さ30cm以上のプランターまたは畑。草丈が高くなる（150cm以上）', 2, '葉・茎・種随時収穫',
     '冷蔵庫野菜室で3〜5日。種は常温で1年保存可',
     '草丈50cm以上で葉・茎を随時収穫。花が咲いたら種も収穫できる',
     '多年草だが高温多湿の日本では一年草として扱うことが多い。ディルと交雑する',
     'Fennel', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest leaves and stems from 50cm+; collect seeds after flowering',
     'Refrigerate 3-5 days; seeds store room temp 1 year',
     'Often grown as annual in humid Japan; cross-pollinates with dill'),
    ('レモンバーム', 4, None, 2, 1, 60, 3, 5, 5, 10,
     '日当たりの良い場所から半日陰まで幅広く対応',
     '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     0.0, 28.0, '苗または株分け', 150, 300,
     '深さ20cm以上のプランター（地植えは広がりすぎることがある）', 0, '随時摘み取り可（多年草）',
     '冷蔵庫野菜室で3〜5日。乾燥保存可（ハーブティー用）',
     '草丈15〜20cmで新芽を随時摘み取り収穫。花穂は早めに摘む',
     'ミントと同様に広がりやすい。高温多湿での病害',
     'Lemon Balm', 'Adaptable from full sun to partial shade',
     'Relatively drought-tolerant; water when surface dries.',
     'Pick young shoots at 15-20cm; pinch flowers to maintain growth',
     'Refrigerate 3-5 days; dry for herbal tea',
     'Can spread aggressively; fungal disease in hot humid conditions'),
    ('セージ', 4, None, 2, 2, 365, 3, 5, 6, 11,
     '直射日光6時間以上。乾燥した環境を好む',
     '乾燥に強い。過湿厳禁。土が乾いてからたっぷりと',
     0.0, 30.0, '苗', 200, 400,
     '深さ20cm以上のプランター。排水性の良い用土', 0, '随時収穫可（多年草）',
     '常温で1週間。乾燥保存可',
     '花が咲く直前〜開花中が最も香りが良い。茎ごと刈り取り',
     '過湿による根腐れ。梅雨時期の管理が重要。3〜4年で株が老化し木質化する',
     'Sage', 'Full sun (6+ hours); prefers dry conditions',
     'Drought-tolerant; overwatering is the main risk.',
     'Harvest stems just before or during flowering for peak aroma',
     'Room temp 1 week; excellent for drying',
     'Root rot from overwatering; woody and unproductive after 3-4 years'),
    ('カモミール', 4, None, 2, 1, 60, 9, 10, 4, 6,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     5.0, 25.0, 'タネ（直播き。秋播きが基本）', 100, 200,
     '深さ15cm以上のプランターまたは畑。一年草（ジャーマンカモミール）', 1, '1株あたり多数の花',
     '乾燥させてハーブティー用に常温保存（1年）',
     '花が開いたらすぐに収穫。朝の収穫が香りが最も強い',
     '高温多湿での立ち枯れ。ジャーマンとローマンの違いに注意（日本では主にジャーマン）',
     'Chamomile', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Harvest flowers as soon as they open; morning harvest has strongest aroma',
     'Dry for herbal tea; store room temp up to 1 year',
     'Damping off in heat and humidity; German vs Roman - different plants'),
    ('ラベンダー', 4, None, 2, 2, 365, 3, 5, 5, 7,
     '直射日光6時間以上。通風の良い場所', '乾燥に強い。過湿厳禁',
     0.0, 25.0, '苗', 200, 500,
     '深さ20cm以上のプランター。排水性の良い用土（アルカリ寄りが理想）', 0, '随時収穫可（多年草）',
     '乾燥保存可（ドライフラワー・ポプリ）',
     '花穂が2〜3割開いたら根元から刈り取り。梅雨前の刈り込みが株を長持ちさせる',
     '日本の高温多湿に弱い（特に夏）。排水不良での根腐れ。関東以西では夏越しが難しい品種あり',
     'Lavender', 'Full sun (6+ hours); good air circulation',
     'Drought-tolerant; waterlogging is fatal.',
     'Harvest flower spikes when 20-30% open; prune before rainy season',
     'Dry for potpourri or sachets; excellent dried',
     'Struggles in hot humid Japanese summers; well-draining alkaline soil essential'),

    # ── 豆類 (category_id=5) ─────────────────────────────────────────
    ('サヤインゲン', 5, None, 1, 1, 60, 4, 6, 7, 9,
     '直射日光6時間以上', '土の表面が乾いたらたっぷりと。開花期の水切れは厳禁',
     18.0, 28.0, 'タネ（直播き）', 100, 150,
     '深さ20cm以上のプランターまたは畑。つる性品種は支柱必要', 2, '1株あたり20〜30本',
     '冷蔵庫野菜室で3〜5日。茹でて冷凍可（1ヶ月）',
     '開花後10〜15日、さやが柔らかく実が小さいうちに収穫。大きくなると固くなる',
     '連作障害。開花期の水切れによる落花。高温期の受粉不良',
     'Green Beans / French Beans', 'Full sun (6+ hours)',
     'Water when surface dries; critical not to let dry during flowering.',
     'Harvest 10-15 days after flowering while pods are still tender',
     'Refrigerate 3-5 days; blanch and freeze up to 1 month',
     'Crop rotation needed; water stress causes flower drop; poor pollination in heat'),
    ('そら豆', 5, None, 1, 2, 180, 10, 11, 4, 6,
     '直射日光6時間以上。冷涼な気候を好む',
     '土の表面が乾いたらたっぷりと。乾燥に弱い',
     5.0, 20.0, 'タネ（秋播き）', 150, 300,
     '深さ30cm以上のプランターまたは畑。株間30〜40cm。支柱が必要', 3, '1株あたり10〜20さや',
     '冷蔵庫野菜室で2〜3日（鮮度落ちが早い）。茹でて冷凍可',
     'さやが上を向いて45度になり、さや表面に黒い筋が入り始めたら収穫',
     '連作障害（アブラムシによるウイルス病媒介）。高温での収穫不良。摘心が必要',
     'Broad Beans / Fava Beans', 'Full sun (6+ hours); prefers cool climate',
     'Water when surface dries; sensitive to drought.',
     'Harvest when pods turn upward at 45° and black lines appear on pod',
     'Refrigerate 2-3 days; freshness fades quickly; blanch and freeze',
     'Aphids spread viruses; poor yield in heat; pinch growing tips to control'),
    ('グリーンピース', 5, None, 1, 2, 150, 10, 11, 4, 6,
     '直射日光6時間以上。冷涼な気候を好む',
     '乾燥に弱い。土の表面が乾いたらたっぷりと',
     5.0, 20.0, 'タネ（秋播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。支柱・ネット必須（つる性）', 2, '1株あたり50〜100g',
     '冷蔵庫野菜室で2〜3日。冷凍保存可（生のまま）',
     'さやが膨らんで実が丸くなったら収穫。実が固くなる前に収穫する',
     '連作障害。高温でのとう立ち。アブラムシ被害',
     'Green Peas', 'Full sun (6+ hours); prefers cool climate',
     'Drought-sensitive; water when surface dries.',
     'Harvest when peas plump up inside pod, before seeds harden',
     'Refrigerate 2-3 days; freeze raw',
     'Crop rotation needed; bolts in heat; aphid damage'),
    ('スナップエンドウ', 5, None, 1, 1, 150, 10, 11, 4, 6,
     '直射日光6時間以上。冷涼な気候を好む',
     '乾燥に弱い。土の表面が乾いたらたっぷりと',
     5.0, 20.0, 'タネ（秋播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。支柱・ネット必須（つる性）', 2, '1株あたり50〜100本',
     '冷蔵庫野菜室で3〜5日。茹でて冷凍可',
     'さやが丸く膨らみ、実が膨らんで張りがあるときに収穫。固くなる前に',
     '連作障害。高温でのとう立ち。うどんこ病',
     'Snap Peas', 'Full sun (6+ hours); prefers cool climate',
     'Drought-sensitive; water when surface dries.',
     'Harvest when pod is plump and firm but before seeds fully harden',
     'Refrigerate 3-5 days; blanch and freeze',
     'Crop rotation needed; bolts in heat; powdery mildew'),
    ('さやえんどう', 5, None, 1, 1, 150, 10, 11, 4, 6,
     '直射日光6時間以上。冷涼な気候を好む',
     '乾燥に弱い。土の表面が乾いたらたっぷりと',
     5.0, 20.0, 'タネ（秋播き）', 100, 150,
     '深さ20cm以上のプランターまたは畑。支柱・ネット必須（つる性）', 2, '1株あたり100〜200本',
     '冷蔵庫野菜室で3〜5日',
     'さやが平らで実が膨らむ前に収穫。さやが厚くなると食感が落ちる',
     '連作障害。高温でのとう立ち。うどんこ病',
     'Snow Peas / Mange-tout', 'Full sun (6+ hours); prefers cool climate',
     'Drought-sensitive; water when surface dries.',
     'Harvest flat pods before peas bulge inside',
     'Refrigerate 3-5 days',
     'Crop rotation needed; bolts in heat; powdery mildew'),
    ('小豆', 5, None, 1, 2, 90, 5, 6, 9, 10,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     18.0, 28.0, 'タネ（直播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。株間20〜25cm', 2, '1株あたり30〜50g',
     '乾燥豆として常温で1年以上保存可',
     'さやが茶色くなり乾燥し始めたら収穫。全株を刈り取り逆さに吊るして乾燥させる',
     '連作障害。過湿による根腐れ。カメムシによる実の食害',
     'Adzuki Beans', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest when pods turn brown and dry; cut whole plant and hang to dry',
     'Dried beans store room temp 1+ year',
     'Crop rotation needed; root rot from overwatering; stink bug damage'),
    ('黒豆', 5, None, 1, 2, 120, 6, 7, 10, 11,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     18.0, 28.0, 'タネ（直播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。株間20〜25cm', 2, '1株あたり50〜100g',
     '乾燥豆として常温で1年以上保存可。枝豆として収穫する場合は冷蔵で3〜5日',
     '乾燥豆：さやが茶色くなり乾燥したら収穫。枝豆収穫：実が膨らんだ緑のうちに',
     '連作障害。カメムシによる実の食害。台風などの風害',
     'Black Soybeans', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Dry beans: harvest when pods turn brown; edamame: pick green while plump',
     'Dried beans: room temp 1+ year; edamame: refrigerate 3-5 days',
     'Crop rotation needed; stink bug damage; wind damage'),
    ('レンズ豆', 5, None, 1, 2, 100, 3, 4, 6, 7,
     '直射日光6時間以上。乾燥した気候を好む',
     '乾燥に強い。過湿厳禁', 5.0, 25.0,
     'タネ（直播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。株間10〜15cm', 2, '1株あたり15〜25g',
     '乾燥豆として常温で1年以上保存可',
     'さやが茶色くなり乾燥し始めたら全株刈り取り。脱粒しやすいため注意',
     '過湿・高温多湿での病害。日本の梅雨に弱い。連作障害',
     'Lentils', 'Full sun (6+ hours); prefers dry climate',
     'Drought-tolerant; avoid overwatering.',
     'Harvest when pods dry and turn brown; handle carefully to avoid shattering',
     'Dried lentils: room temp 1+ year',
     'Poorly suited to Japans humid rainy season; crop rotation needed'),
    ('ひよこ豆', 5, None, 1, 2, 100, 3, 4, 6, 7,
     '直射日光6時間以上', '乾燥に強い。過湿は厳禁',
     10.0, 28.0, 'タネ（直播き）', 100, 200,
     '深さ20cm以上のプランターまたは畑。株間20〜25cm', 2, '1株あたり20〜40g',
     '乾燥豆として常温で1年以上保存可',
     'さやが乾燥し始めたら全株刈り取り。緑のうちに収穫してもOK（フレッシュひよこ豆）',
     '日本の高温多湿（梅雨）に弱い。連作障害。アブラムシ被害',
     'Chickpeas / Garbanzo Beans', 'Full sun (6+ hours)',
     'Drought-tolerant; waterlogging is harmful.',
     'Harvest when pods dry; can also harvest green for fresh eating',
     'Dried: room temp 1+ year',
     'Struggles in Japans humid summers; crop rotation; aphids'),
    ('白花豆', 5, None, 1, 2, 120, 5, 6, 9, 10,
     '直射日光6時間以上。高温を好む',
     '水を好む。土の表面が乾いたらたっぷりと',
     18.0, 28.0, 'タネ（直播き）', 100, 200,
     '大型プランター（30L以上）または畑。つる性のため支柱・ネット必須', 3, '1株あたり50〜100g',
     '乾燥豆として常温で1年以上保存可',
     'さやが茶色くなり乾燥したら収穫。全株刈り取り後に乾燥させる',
     '高温障害（40℃超での落花）。連作障害。カメムシ被害',
     'White Runner Beans / Shiro-hana-mame', 'Full sun (6+ hours); loves warmth',
     'Water when surface dries.',
     'Harvest when pods turn brown and dry; hang whole plant to finish drying',
     'Dried: room temp 1+ year',
     'Flower drop in extreme heat (40°C+); crop rotation; stink bugs'),

    # ── イモ類 (category_id=6) ──────────────────────────────────────
    ('キクイモ', 6, None, 1, 1, 180, 3, 4, 10, 12,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     5.0, 28.0, '塊茎（食用のものを種芋にできる）', 150, 300,
     '畑栽培または大型プランター（50L以上）。多年草で毎年収穫可（地植え）', 0, '1株あたり500g〜2kg',
     '土の中に埋めたまま保存（冬中）。掘り出したら冷蔵で2〜3週間',
     '葉が黄色く枯れ始めた秋〜冬に塊茎を掘り出して収穫',
     '地下茎で広がりすぎる（プランター管理推奨）。生育旺盛で草丈が2m以上になる',
     'Jerusalem Artichoke', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest tubers in autumn when leaves yellow and die back',
     'Store in ground through winter; refrigerate once dug for 2-3 weeks',
     'Invasive via underground spread; grows very tall (2m+)'),
    ('こんにゃく', 6, None, 1, 3, 1095, 4, 5, 10, 11,
     '半日陰でも育つ。直射日光より木陰が理想',
     '水を好む。土を乾かさないよう管理',
     15.0, 28.0, '球茎（生子・きご）', 500, 1000,
     '畑栽培が基本。深さ30cm以上の大型プランターも可', 0, '1株あたり1〜3kg（3年かかる）',
     '涼しい場所で常温保存（1ヶ月）または冷蔵で3ヶ月',
     '葉が枯れた秋に球茎を掘り出して収穫。収穫できる大きさになるまで3年かかる',
     '栽培に3年必要（市販品は加工が必要で家庭では難易度が高い）。軟腐病',
     'Konjac', 'Tolerates partial shade; prefers dappled light',
     'Keep soil moist.',
     'Harvest corms in autumn when leaves die; takes 3 years to reach harvest size',
     'Cool storage 1 month at room temp; refrigerate up to 3 months',
     'Requires 3 years to grow; processing needed; soft rot disease'),
    ('クワイ', 6, None, 1, 2, 180, 4, 5, 11, 12,
     '直射日光8時間以上', '水生植物。水深5〜10cmを維持する',
     15.0, 28.0, '球茎', 300, 600,
     '水はけの悪い場所または水を張ったプランター・睡蓮鉢', 2, '1株あたり10〜30個',
     '冷蔵庫野菜室で2〜3週間',
     '葉が枯れた11〜12月に泥の中から掘り出して収穫',
     '水量管理が難しい。泥の中での栽培で管理が大変',
     'Arrowhead / Kuwai', 'Full sun (8+ hours)',
     'Aquatic plant; maintain 5-10cm water depth.',
     'Harvest corms in Nov-Dec when leaves die back',
     'Refrigerate 2-3 weeks',
     'Water level management; muddy growing conditions'),
    ('ヤーコン', 6, None, 1, 2, 180, 4, 5, 10, 11,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     10.0, 28.0, '塊茎（前年の株の根茎を使用）', 300, 600,
     '深さ40cm以上のプランターまたは畑。株間60〜80cm', 2, '1株あたり1〜3kg',
     '冷蔵庫野菜室で2〜3週間。収穫後2〜3週間追熟させると甘みが増す',
     '葉が黄色く枯れ始めた秋〜初冬に芋を掘り出す。追熟で甘みが増す',
     '草丈が2m以上になり支柱が必要。強風で倒れやすい。芋が光に当たると緑変する',
     'Yacon', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Harvest tubers in autumn when leaves yellow; cure 2-3 weeks to increase sweetness',
     'Refrigerate 2-3 weeks after curing',
     'Grows 2m+ tall (staking needed); tubers turn green in light'),
    ('タロイモ', 6, None, 1, 2, 180, 4, 5, 10, 11,
     '直射日光6時間以上。高温多湿を好む',
     '水を非常に好む。土を常に湿らせた状態で管理',
     20.0, 30.0, '球茎（親芋または子芋）', 200, 400,
     '深さ30cm以上の大型プランターまたは畑。高温多湿な場所が理想', 2, '1株あたり1〜2kg',
     '常温で1〜2ヶ月。冷蔵は不向き（低温障害）',
     '葉が黄色く枯れ始めた秋に塊茎を掘り出して収穫',
     '低温（15℃以下）での生育停止。日本の冬に弱い。アク（シュウ酸カルシウム）が多い',
     'Taro', 'Full sun (6+ hours); loves heat and humidity',
     'Keep soil consistently moist.',
     'Harvest corms in autumn when leaves yellow',
     'Room temp 1-2 months; refrigeration causes chilling injury',
     'Growth stops below 15°C; high calcium oxalate (causes itching when raw)'),
    ('ムカゴ', 6, None, 1, 1, 180, 3, 4, 9, 10,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     10.0, 28.0, 'ムカゴ（山芋のつるにつく球芽）または種芋', 200, 400,
     '深さ60cm以上のプランターまたは畑。つる性のため支柱・ネット必須', 2, '1株あたり10〜50個（ムカゴ）',
     '冷蔵庫野菜室で1〜2週間。乾燥保存可',
     '秋にムカゴが茶色くなり自然に落ちるころ収穫。芋は葉が枯れてから掘る',
     '山芋・自然薯の栽培難易度と同じ。地下茎が深く伸びるため収穫が大変',
     'Mukago / Aerial Yam Bulbils', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Collect bulbils when they turn brown and fall naturally in autumn',
     'Refrigerate 1-2 weeks; can be dried',
     'Same difficulty as growing yam; deep roots make harvesting laborious'),
    ('ツクネイモ', 6, None, 1, 2, 180, 4, 5, 10, 11,
     '直射日光6時間以上', '乾燥に比較的強い。土の表面が乾いたらたっぷりと',
     15.0, 28.0, '種芋（塊茎）', 300, 600,
     '深さ40〜50cm以上のプランターまたは畑（長いもより短く作れる）', 3, '1株あたり500g〜1kg',
     '冷暗所で1〜2ヶ月。冷蔵庫で2〜3ヶ月',
     '葉が黄色く枯れた後、霜が降りる前に掘り出す。丸く固い芋を収穫',
     '連作障害。深根性だが長いもより掘りやすい。高温多湿での病害',
     'Tsukune Yam / Round Yam', 'Full sun (6+ hours)',
     'Relatively drought-tolerant; water when surface dries.',
     'Harvest before frost when leaves die back; round and firm',
     'Cool dark storage 1-2 months; refrigerate 2-3 months',
     'Crop rotation needed; more compact than nagaimo but still needs depth'),
    ('自然薯', 6, None, 1, 3, 180, 4, 5, 10, 11,
     '直射日光6時間以上', '乾燥に強い。土の表面が乾いたらたっぷりと',
     10.0, 28.0, '種芋（むかご・小塊茎）', 300, 800,
     '深さ100cm以上の深型プランターまたは波板を使った斜め栽培が必要', 3, '1株あたり300〜700g',
     '冷暗所で1〜2ヶ月。冷蔵庫で2〜3ヶ月',
     '葉が枯れた秋〜冬に掘り出す。折れないよう丁寧に。長さ50〜100cmになる',
     '栽培難易度が最も高いイモの一つ。深さ100cm以上の土壌が必要。折れやすい',
     'Wild Japanese Yam / Jinenjo', 'Full sun (6+ hours)',
     'Drought-tolerant; water when surface dries.',
     'Harvest in autumn after leaves die; dig carefully to avoid breaking long roots',
     'Cool dark storage 1-2 months; refrigerate 2-3 months',
     'Requires 100cm+ deep soil; roots break easily; very challenging to grow'),
    ('キャッサバ', 6, None, 1, 3, 270, 4, 5, 10, 11,
     '直射日光8時間以上。高温を好む',
     '乾燥に強い。過湿は厳禁',
     20.0, 35.0, '茎（挿し木）', 300, 600,
     '畑栽培（沖縄・南九州向き）。大型プランター（100L以上）でも可', 2, '1株あたり2〜5kg',
     '常温で1週間（生）。調理後は冷凍可',
     '葉が落ちた後、霜の前に芋を掘り出す。白く固い塊茎を収穫',
     '低温（15℃以下）での枯死。本州では越冬が難しい。生食不可（加熱必須）',
     'Cassava / Tapioca', 'Full sun (8+ hours); heat-loving',
     'Drought-tolerant; avoid overwatering.',
     'Harvest before frost when leaves drop; white firm tubers',
     'Fresh: room temp 1 week; cook and freeze',
     'Dies below 15°C (suited for Okinawa/south Kyushu); must be cooked before eating'),
]


def main():
    today = date.today().isoformat()
    conn = sqlite3.connect(DB)
    cur = conn.cursor()

    cur.execute('SELECT name FROM crops')
    existing = {r[0] for r in cur.fetchall()}

    added = 0
    skipped = 0
    for c in CROPS:
        name = c[0]
        if name in existing:
            skipped += 1
            continue
        cur.execute('''
            INSERT INTO crops (
                name, category_id, region_id, environment_id, difficulty, days_to_harvest,
                sow_start, sow_end, harvest_start, harvest_end,
                sunlight, watering, temp_min, temp_max,
                seed_or_seedling, price_min, price_max, planter_size,
                rotation_years, yield_per_plant, storage, harvest_sign, failure_points,
                source_url, fetched_at,
                name_en, sunlight_en, watering_en, harvest_sign_en, storage_en, failure_points_en
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        ''', (
            c[0], c[1], c[2], c[3], c[4], c[5],
            c[6], c[7], c[8], c[9],
            c[10], c[11], c[12], c[13],
            c[14], c[15], c[16], c[17],
            c[18], c[19], c[20], c[21], c[22],
            '', today,
            c[23], c[24], c[25], c[26], c[27], c[28],
        ))
        added += 1

    conn.commit()
    conn.close()
    print(f'追加: {added}件 / スキップ（既存）: {skipped}件')

    conn = sqlite3.connect(DB)
    cur = conn.cursor()
    cur.execute('SELECT COUNT(*) FROM crops')
    total = cur.fetchone()[0]
    conn.close()
    print(f'crops合計: {total}件')


if __name__ == '__main__':
    main()
